export const localImage = {
  Fart: require('../../src/Icon/Image/fart.jpg'),
  Fart1: require('../../src/Icon/Image/fart1.png'),
  Scary: require('../../src/Icon/Image/scary.png'),
  Hair: require('../../src/Icon/Image/hair.png'),
  Airhorn: require('../../src/Icon/Image/airhorn.png'),
  Mosquito: require('../../src/Icon/Image/mosquito.png'),
  Laughing: require('../../src/Icon/Image/laughing.png'),
  Dog: require('../../src/Icon/Image/dog.png'),
  Babycry: require('../../src/Icon/Image/babycry.png'),
  Gun: require('../../src/Icon/Image/gun.png'),
  Police: require('../../src/Icon/Image/police.png'),
  Snoring: require('../../src/Icon/Image/snoring.png'),
  Sneeze: require('../../src/Icon/Image/sneeze.png'),
  Breaking: require('../../src/Icon/Image/breaking.png'),
  Caugh: require('../../src/Icon/Image/caugh.png'),
  Toilet: require('../../src/Icon/Image/toilet.png'),
  Scissors: require('../../src/Icon/Image/scissors.png'),
  Hairdryer: require('../../src/Icon/Image/hairdryer.png'),
  Notification: require('../../src/Icon/Image/notification.png'),
  Dor: require('../../src/Icon/Image/dor.png'),
  Car: require('../../src/Icon/Image/car.png'),
  Brup: require('../Icon/Image/bru.png'),
};
